### ISSUE TITLE
FileNotFoundError in Pycharm

### ISSUE THREAD

**Issue by calebheinzman** [Deep-Stonks-Group/Forecasting-Team-1#26]
Traceback (most recent call last):
  File "/Users/calebheinzman/Documents/Workspace/PyCharm Projects/Stocks/Forecasting-Team-1/simple_lstm/torchLSTM.py", line 174, in <module>
    predictor.load_model('AAPL')
  File "/Users/calebheinzman/Documents/Workspace/PyCharm Projects/Stocks/Forecasting-Team-1/simple_lstm/torchLSTM.py", line 105, in load_model
    with open('simple_lstm/models/' + name + '.p', 'rb') as infile:
FileNotFoundError

**Comment by calebheinzman** [comment]
If you are using pycharm you need to set the working directory at the root Forecast-Team-1 folder.

1. Go to the top right next to the run button where you added the torchLSTM file.
2. Click the drop down and click 'Edit Configurtations'.
3. Under the 'Environment' section, find 'Working Directory'.
4. Change the directory to 'Forecast-Team-1'
